feat: add SilentSignin and AuthCallback components
casdoor/casdoor-react-sdk pull request #1
Opened 2022-08-28 17:26 UTC by wenxuan70

Referring to the `SilentSignin` function of casnode, put the universal components in the SDK.

https://github.com/casbin/casnode/blob/d526c9ae001057a3976c7a16a4a4e9a359d85ed4/web/src/App.js#L606-L628

2022-08-29 17:02 UTC, hsluoyz requested changes

2022-08-29 17:02 UTC, hsluoyz commented on src/AuthCallback.tsx
> +import * as React from "react";
license header for all files

2022-08-29 17:02 UTC, hsluoyz commented on src/SilentSignin.tsx
> +import * as React from "react";
Why not .ts?

2022-08-29 17:02 UTC, hsluoyz commented on yarn.lock
> +  resolved "https://registry.npmmirror.com/@ampproject/remapping/-/remapping-2.2.0.tgz#56c133824780de3174aed5ab6834f3026790154d"
yarnpkg.com

2022-08-29 17:14 UTC, hsluoyz requested changes

2022-08-29 17:14 UTC, hsluoyz commented on tsconfig.json
> +{
Add README.md

2022-08-31 15:50 UTC, wenxuan70 commented on src/SilentSignin.tsx
> +import * as React from "react";
.ts will cause compilation to fail.

2022-09-01 04:20 UTC, merged